micronaut:
  metrics.binders:
    jvm.enabled: true
    web.enabled: true
    processor.enabled: true
    jdbc.enabled: false
  security:
    enabled: true
    token.jwt:
      enabled: true
      bearer.enabled: true
  caches:
    identity-cache:
      expire-after-write: 10m
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  executors:
    io:
      type: fixed
      nThreads: 6

endpoints:
  all:
    enabled: true
    path: /endpoints
    sensitive: false

persistence:
  compact:
    schedule.cron: "0 14 2 1/1 * ?"
    deletions:
      enabled: false
      threshold: 1d
  read:
    limit: 1000
    max-batch-size: 2000000
    retry-after: 10000
    expected-node-count: 3000
    cluster-db-pool-size: 60
    work-mem-mb: 512


authentication:
  users:
    pipe-provider-live:
      password: "${PIPE_READ_PASSWORD}"
    pipe-runscope-live:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    live-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_NODE
        - PIPE_READ
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_TOKEN_PATH}"
    issue.token.path: "${IDENTITY_ISSUE_TOKEN_PATH}"
    delay: 500ms
    multiplier: 3
    max-delay: 15m
    reset: 300ms
    attempts: 3
    client:
      id: "${IDENTITY_CLIENT_ID}"
      secret: "${IDENTITY_CLIENT_SECRET}"
    users:
      nodeA:
        clientId: "${NODE_A_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

location:
  url: "${LOCATION_URL}"
  attempts: 3
  delay: 500ms
  reset: 5s

pipe:
  server:
    url: "https://api.tesco.com/messaging/v1"

compression:
  threshold-in-bytes: 1024
  logging: true
